export enum Rarity {
  COMMON = 'Common',
  RARE = 'Rare',
  EPIC = 'Epic',
  LEGENDARY = 'Legendary'
}

export interface PokemonStats {
  hp: number;
  attack: number;
  defense: number;
  speed: number;
}

export interface Pokemon {
  id: string; // Unique instance ID
  pokedexId: number;
  name: string;
  image: string;
  types: string[];
  stats: PokemonStats;
  rarity: Rarity;
  obtainedAt: number;
  description?: string; // Generated by Gemini
  personality?: string; // Generated by Gemini for chat context
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'pokemon';
  text: string;
  timestamp: number;
}
